name = "Clojure"
grammar = "clojure"
path_suffixes = ["clj", "cljs", "cljc", "cljd", "edn", "bb", "lpy"]
line_comments = [";; "]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
word_characters = ["-"]
